version: "3.7"
services:
  nginx:
    image: nhumnl.azurecr.io/portfolio/nginx
    environment:
      NGINX_PORT: 80
    ports:
      - "80:80"
    depends_on:
      - react
  react:
    image: nhumnl.azurecr.io/portfolio/react
    environment:
      NODE_ENV: production
    command: npm run start