version: "3.7"
services:
  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    environment:
      NGINX_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - react
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
  react:
    build: 
      context: .
      dockerfile: react.dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - ./.env
    command: npm start