version: "3.7"
services:
  nginx:
    build: 
      context: .
      dockerfile: nginx.dockerfile
    environment:
      NGINX_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - react
  react:
    build: 
      context: .
      dockerfile: react.dockerfile
    command: npm run start